{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "webapp_test.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "toc_visible": true,
      "authorship_tag": "ABX9TyP0PpQ6jdyxStSFNENnv8Eu",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/delemarchand2020/testColab/blob/main/webapp_test.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "j3hl24JUfvnI"
      },
      "source": [
        "\r\n",
        "\r\n",
        "Voir doc : https://medium.com/@arsindoliya/running-django-on-google-colab-ea9392cdee86\r\n",
        "\r\n"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "mKH0NZ5FA3U4",
        "outputId": "185a7128-81d2-479e-e28f-95a1082ad3ad"
      },
      "source": [
        "!pip install django"
      ],
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: django in /usr/local/lib/python3.6/dist-packages (3.1.5)\n",
            "Requirement already satisfied: asgiref<4,>=3.2.10 in /usr/local/lib/python3.6/dist-packages (from django) (3.3.1)\n",
            "Requirement already satisfied: sqlparse>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from django) (0.4.1)\n",
            "Requirement already satisfied: pytz in /usr/local/lib/python3.6/dist-packages (from django) (2018.9)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "TjfyL1qnA6Jn"
      },
      "source": [
        "!django-admin startproject webapp_test"
      ],
      "execution_count": 2,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "jGwNySoChQNf",
        "outputId": "18314541-5458-4c15-8fc3-cc2ee02c189f"
      },
      "source": [
        "!webapp_test/manage.py migrate"
      ],
      "execution_count": 14,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "\u001b[36;1mOperations to perform:\u001b[0m\n",
            "\u001b[1m  Apply all migrations: \u001b[0madmin, auth, contenttypes, sessions\n",
            "\u001b[36;1mRunning migrations:\u001b[0m\n",
            "  No migrations to apply.\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "3v7OTddqhZ1g"
      },
      "source": [
        "!webapp_test/manage.py startapp polls"
      ],
      "execution_count": 4,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "qGrxcCLJXuOe"
      },
      "source": [
        "!mv polls webapp_test/"
      ],
      "execution_count": 5,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "zx4lzOcVeEs3",
        "outputId": "bfbbe2c4-d651-4384-b718-05754053f15a"
      },
      "source": [
        "!ls webapp_test"
      ],
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "db.sqlite3  manage.py  polls  webapp_test\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "DLd_cnq7aT9t"
      },
      "source": [
        "Faire ceci : https://docs.djangoproject.com/en/3.1/intro/tutorial01/#write-your-first-view"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 35
        },
        "id": "tbQS5t9eeTyb",
        "outputId": "7d364508-16fc-4db9-bdec-79aa0d246d34"
      },
      "source": [
        "from google.colab.output import eval_js\r\n",
        "print(eval_js(\"google.colab.kernel.proxyPort(8000)\")+\"polls/\")"
      ],
      "execution_count": 17,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "https://k7mrg1mj15i-496ff2e9c6d22116-8000-colab.googleusercontent.com/polls/\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "qzPoI2fee2p3",
        "outputId": "39fb6c27-e17a-47b8-ceb3-97e1ba31542c"
      },
      "source": [
        "!webapp_test/manage.py runserver 8000"
      ],
      "execution_count": 19,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 22:57:56\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/views.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 22:58:25\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/views.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 22:58:35\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 22:58:38] \u001b[m\"GET /polls/ HTTP/1.1\" 200 28\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 22:58:38] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 22:58:42] \u001b[m\"GET /polls/ HTTP/1.1\" 200 28\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 22:58:42] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "/content/webapp_test/polls/views.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 22:58:51\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/views.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 22:58:54\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 22:58:56] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 22:58:56] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "/content/webapp_test/polls/views.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 22:59:11\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 22:59:47] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 22:59:48] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:00:04] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:00:04] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:00:07] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:00:07] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:01:16] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:01:17] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:01:26] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:01:27] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:01:58] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:01:59] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:02:16] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:02:16] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:02:18] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:02:19] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:03:08] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:03:08] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:03:32] \u001b[32m\"GET /polls HTTP/1.1\" 301 0\u001b[0m\n",
            "[12/Jan/2021 23:03:37] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:03:38] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:05:47] \u001b[32m\"GET /admin/ HTTP/1.1\" 302 0\u001b[0m\n",
            "[12/Jan/2021 23:06:03] \u001b[32m\"GET /admin HTTP/1.1\" 301 0\u001b[0m\n",
            "[12/Jan/2021 23:06:08] \u001b[32m\"GET /admin/ HTTP/1.1\" 302 0\u001b[0m\n",
            "[12/Jan/2021 23:07:06] \u001b[32m\"GET /admin/ HTTP/1.1\" 302 0\u001b[0m\n",
            "Not Found: /pools/\n",
            "[12/Jan/2021 23:07:15] \u001b[33m\"GET /pools/ HTTP/1.1\" 404 2081\u001b[0m\n",
            "[12/Jan/2021 23:07:22] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "[12/Jan/2021 23:07:24] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:07:25] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "Not Found: /polls/admin\n",
            "[12/Jan/2021 23:08:28] \u001b[33m\"GET /polls/admin HTTP/1.1\" 404 2157\u001b[0m\n",
            "Not Found: /polls/admin/\n",
            "[12/Jan/2021 23:08:34] \u001b[33m\"GET /polls/admin/ HTTP/1.1\" 404 2160\u001b[0m\n",
            "[12/Jan/2021 23:08:44] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:08:44] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:17:51] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:17:52] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:17:53] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:17:54] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:18:20] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:18:20] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:18:33] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:18:34] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:18:37] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:18:38] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:19:07] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:19:08] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:19:38] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:19:39] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:20:01] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:20:02] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:20:31] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:20:32] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:21:02] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:21:02] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "[12/Jan/2021 23:21:04] \u001b[m\"GET /polls/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:21:05] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2096\u001b[0m\n",
            "/content/webapp_test/webapp_test/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:22:32\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/webapp_test/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:22:40\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "Not Found: /polls/\n",
            "[12/Jan/2021 23:22:41] \u001b[33m\"GET /polls/ HTTP/1.1\" 404 2076\u001b[0m\n",
            "Not Found: /\n",
            "[12/Jan/2021 23:22:47] \u001b[33m\"GET / HTTP/1.1\" 404 2040\u001b[0m\n",
            "Not Found: /\n",
            "[12/Jan/2021 23:23:01] \u001b[33m\"GET / HTTP/1.1\" 404 2040\u001b[0m\n",
            "Not Found: /\n",
            "[12/Jan/2021 23:23:08] \u001b[33m\"GET / HTTP/1.1\" 404 2040\u001b[0m\n",
            "Not Found: /polls/\n",
            "[12/Jan/2021 23:23:17] \u001b[33m\"GET /polls/ HTTP/1.1\" 404 2076\u001b[0m\n",
            "Not Found: /polls/\n",
            "[12/Jan/2021 23:23:18] \u001b[33m\"GET /polls/ HTTP/1.1\" 404 2076\u001b[0m\n",
            "Not Found: /\n",
            "[12/Jan/2021 23:23:25] \u001b[33m\"GET / HTTP/1.1\" 404 2040\u001b[0m\n",
            "Not Found: /\n",
            "[12/Jan/2021 23:23:27] \u001b[33m\"GET / HTTP/1.1\" 404 2040\u001b[0m\n",
            "/content/webapp_test/webapp_test/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified some issues:\n",
            "\n",
            "WARNINGS:\n",
            "\u001b[33;1m?: (urls.W002) Your URL pattern '^/site' has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.\u001b[0m\n",
            "\n",
            "System check identified 1 issue (0 silenced).\n",
            "January 12, 2021 - 23:23:48\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/webapp_test/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified some issues:\n",
            "\n",
            "WARNINGS:\n",
            "\u001b[33;1m?: (urls.W002) Your URL pattern '^/site' has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.\u001b[0m\n",
            "\n",
            "System check identified 1 issue (0 silenced).\n",
            "January 12, 2021 - 23:23:53\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/webapp_test/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:24:14\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/webapp_test/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:24:18\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:24:23] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:24:23] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/webapp_test/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:24:38\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:25:00] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:25:00] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/views.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:29:10\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:29:25\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:29:55\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:30:07\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:30:20\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:30:20] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:30:21] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:31:08\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/webapp_test/settings.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:32:02\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:34:48] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:34:48] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:34:50] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:34:50] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:35:22] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:35:22] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:35:23] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:35:24] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:39:06\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:39:23\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:39:28\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:40:04\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:40:07\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:40:07] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:40:08] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:40:17\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:40:30] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:40:30] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:40:32] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:40:33] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:40:33] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:40:34] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:41:02] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:41:03] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:41:04] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:41:05] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.6/threading.py\", line 864, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py\", line 53, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/management/commands/runserver.py\", line 118, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/management/base.py\", line 396, in check\n",
            "    databases=databases,\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/registry.py\", line 70, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py\", line 13, in check_url_config\n",
            "    return check_resolver(resolver)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py\", line 23, in check_resolver\n",
            "    return check_method()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 408, in check\n",
            "    for pattern in self.url_patterns:\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/functional.py\", line 48, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 589, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/functional.py\", line 48, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 582, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
            "  File \"/content/webapp_test/webapp_test/urls.py\", line 20, in <module>\n",
            "    url(r'^site/', include('polls.urls')),\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/conf.py\", line 34, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
            "  File \"/content/webapp_test/polls/urls.py\", line 9, in <module>\n",
            "    url(r'^favicon\\.ico$', RedirectView.as_view(url='/img/favicon.ico'))\n",
            "NameError: name 'url' is not defined\n",
            "\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.6/threading.py\", line 864, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py\", line 53, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/management/commands/runserver.py\", line 118, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/management/base.py\", line 396, in check\n",
            "    databases=databases,\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/registry.py\", line 70, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py\", line 13, in check_url_config\n",
            "    return check_resolver(resolver)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py\", line 23, in check_resolver\n",
            "    return check_method()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 408, in check\n",
            "    for pattern in self.url_patterns:\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/functional.py\", line 48, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 589, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/functional.py\", line 48, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 582, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
            "  File \"/content/webapp_test/webapp_test/urls.py\", line 20, in <module>\n",
            "    url(r'^site/', include('polls.urls')),\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/conf.py\", line 34, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
            "  File \"/content/webapp_test/polls/urls.py\", line 1, in <module>\n",
            "    from django.urls import path, url\n",
            "ImportError: cannot import name 'url'\n",
            "\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.6/threading.py\", line 864, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py\", line 53, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/management/commands/runserver.py\", line 118, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/management/base.py\", line 396, in check\n",
            "    databases=databases,\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/registry.py\", line 70, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py\", line 13, in check_url_config\n",
            "    return check_resolver(resolver)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py\", line 23, in check_resolver\n",
            "    return check_method()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 408, in check\n",
            "    for pattern in self.url_patterns:\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/functional.py\", line 48, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 589, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/functional.py\", line 48, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 582, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
            "  File \"/content/webapp_test/webapp_test/urls.py\", line 20, in <module>\n",
            "    url(r'^site/', include('polls.urls')),\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/conf.py\", line 34, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
            "  File \"/content/webapp_test/polls/urls.py\", line 9, in <module>\n",
            "    url(r'^favicon\\.ico$', RedirectView.as_view(url='/img/favicon.ico'))\n",
            "NameError: name 'url' is not defined\n",
            "\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.6/threading.py\", line 864, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py\", line 53, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/management/commands/runserver.py\", line 118, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/management/base.py\", line 396, in check\n",
            "    databases=databases,\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/registry.py\", line 70, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py\", line 13, in check_url_config\n",
            "    return check_resolver(resolver)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py\", line 23, in check_resolver\n",
            "    return check_method()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 408, in check\n",
            "    for pattern in self.url_patterns:\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/functional.py\", line 48, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 589, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/functional.py\", line 48, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 582, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
            "  File \"/content/webapp_test/webapp_test/urls.py\", line 20, in <module>\n",
            "    url(r'^site/', include('polls.urls')),\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/conf.py\", line 34, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
            "  File \"/content/webapp_test/polls/urls.py\", line 9, in <module>\n",
            "    url(r'^favicon\\.ico$', RedirectView.as_view(url='/img/favicon.ico'))\n",
            "NameError: name 'url' is not defined\n",
            "\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "Exception in thread django-main-thread:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.6/threading.py\", line 864, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py\", line 53, in wrapper\n",
            "    fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/management/commands/runserver.py\", line 118, in inner_run\n",
            "    self.check(display_num_errors=True)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/management/base.py\", line 396, in check\n",
            "    databases=databases,\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/registry.py\", line 70, in run_checks\n",
            "    new_errors = check(app_configs=app_configs, databases=databases)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py\", line 13, in check_url_config\n",
            "    return check_resolver(resolver)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py\", line 23, in check_resolver\n",
            "    return check_method()\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 408, in check\n",
            "    for pattern in self.url_patterns:\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/functional.py\", line 48, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 589, in url_patterns\n",
            "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/utils/functional.py\", line 48, in __get__\n",
            "    res = instance.__dict__[self.name] = self.func(instance)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py\", line 582, in urlconf_module\n",
            "    return import_module(self.urlconf_name)\n",
            "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
            "  File \"/content/webapp_test/webapp_test/urls.py\", line 20, in <module>\n",
            "    url(r'^site/', include('polls.urls')),\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/django/urls/conf.py\", line 34, in include\n",
            "    urlconf_module = import_module(urlconf_module)\n",
            "  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
            "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 674, in exec_module\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 781, in get_code\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 741, in source_to_code\n",
            "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
            "  File \"/content/webapp_test/polls/urls.py\", line 2\n",
            "    from django.conf.urls import url,\n",
            "                                ^\n",
            "SyntaxError: trailing comma not allowed without surrounding parentheses\n",
            "\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:42:48\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:42:53\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:42:59] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:43:00] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:43:01] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:43:02] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:43:52\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:43:57\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:43:57] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:43:57] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:44:17\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:45:00\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:45:06] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:45:07] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:45:09] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:45:09] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:46:02] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:46:02] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:46:15] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:46:16] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:46:17] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:46:17] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:46:17] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:46:18] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:46:28] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:46:28] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:47:01\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "Not Found: /site/img/favicon.ico\n",
            "[12/Jan/2021 23:47:08] \u001b[33m\"GET /site/img/favicon.ico HTTP/1.1\" 404 2348\u001b[0m\n",
            "Not Found: /site/img/\n",
            "[12/Jan/2021 23:47:27] \u001b[33m\"GET /site/img/ HTTP/1.1\" 404 2315\u001b[0m\n",
            "Not Found: /site/img/favicon.ico\n",
            "[12/Jan/2021 23:47:35] \u001b[33m\"GET /site/img/favicon.ico HTTP/1.1\" 404 2348\u001b[0m\n",
            "Not Found: /site/img/favicon.ico\n",
            "[12/Jan/2021 23:47:39] \u001b[33m\"GET /site/img/favicon.ico HTTP/1.1\" 404 2348\u001b[0m\n",
            "[12/Jan/2021 23:47:47] \u001b[32m\"GET /site/favicon.ico HTTP/1.1\" 302 0\u001b[0m\n",
            "[12/Jan/2021 23:47:55] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:47:55] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:48:17\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:48:20\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:48:21] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:48:21] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified some issues:\n",
            "\n",
            "WARNINGS:\n",
            "\u001b[33;1m?: (urls.W002) Your URL pattern '/favicon.ico' has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.\u001b[0m\n",
            "\n",
            "System check identified 1 issue (0 silenced).\n",
            "January 12, 2021 - 23:48:36\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified some issues:\n",
            "\n",
            "WARNINGS:\n",
            "\u001b[33;1m?: (urls.W002) Your URL pattern '/favicon.ico' has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.\u001b[0m\n",
            "\n",
            "System check identified 1 issue (0 silenced).\n",
            "January 12, 2021 - 23:48:42\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:48:51\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:48:57\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:48:57] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:48:57] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:48:58] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:48:59] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "/content/webapp_test/polls/urls.py changed, reloading.\n",
            "Watching for file changes with StatReloader\n",
            "Performing system checks...\n",
            "\n",
            "System check identified no issues (0 silenced).\n",
            "January 12, 2021 - 23:49:16\n",
            "Django version 3.1.5, using settings 'webapp_test.settings'\n",
            "Starting development server at http://127.0.0.1:8000/\n",
            "Quit the server with CONTROL-C.\n",
            "[12/Jan/2021 23:49:22] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:49:22] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n",
            "[12/Jan/2021 23:50:04] \u001b[m\"GET /site/ HTTP/1.1\" 200 30\u001b[0m\n",
            "Not Found: /favicon.ico\n",
            "[12/Jan/2021 23:50:04] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2095\u001b[0m\n"
          ],
          "name": "stdout"
        }
      ]
    }
  ]
}